# syntax=docker/dockerfile:1
FROM node:24-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Build the specific service
RUN pnpm --filter=@smr/payment-service build

# Use pnpm deploy to create a pruned standalone directory
RUN pnpm --filter=@smr/payment-service --prod deploy /app

FROM base AS runner
WORKDIR /app

# Copy built files and dependencies from the deploy directory
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json

EXPOSE 4000

CMD ["node", "dist/index.js"]
