# syntax=docker/dockerfile:1
FROM node:24-slim AS base
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

FROM base AS api-gateway-builder
WORKDIR /app
COPY tsconfig.base.json ./
WORKDIR /app/smr-backend/api-gateway
COPY ./smr-backend/api-gateway/package.json ./smr-backend/api-gateway/tsconfig.json ./

RUN --mount=type=cache,target=/root/.npm npm install
RUN --mount=type=cache,target=/root/.npm npm install --save-dev typescript @types/node @types/express @types/cors @types/jsonwebtoken @types/morgan

COPY ./smr-backend/api-gateway/src ./src
RUN npm run build -- --noEmit false

FROM base AS api-gateway-prod
USER node
WORKDIR /app
ENV NODE_ENV=production
COPY --chown=node:node ./smr-backend/api-gateway/package.json ./package.json
RUN --mount=type=cache,target=/home/node/.npm,uid=1000,gid=1000 npm install --omit=dev
COPY --chown=node:node --from=api-gateway-builder /app/smr-backend/api-gateway/dist/ ./dist
EXPOSE 4000
CMD ["node", "--conditions", "production", "dist/src/index.js"]



# --- 2. User Service ---
FROM base AS user-service-builder
WORKDIR /app
COPY tsconfig.base.json ./
WORKDIR /app/smr-backend/user-service
COPY ./smr-backend/user-service/package.json ./smr-backend/user-service/tsconfig.json ./
RUN --mount=type=cache,target=/root/.npm npm install
RUN --mount=type=cache,target=/root/.npm npm install --save-dev typescript @types/node @types/express @types/cors @types/jsonwebtoken @types/morgan @types/amqplib
COPY ./smr-backend/user-service/src ./src
RUN npm run build -- --noEmit false

FROM base AS user-service-prod
USER node
WORKDIR /app
ENV NODE_ENV=production
COPY --chown=node:node ./smr-backend/user-service/package.json ./package.json
RUN --mount=type=cache,target=/home/node/.npm,uid=1000,gid=1000 npm install --omit=dev
COPY --chown=node:node --from=user-service-builder /app/smr-backend/user-service/dist/ ./dist
EXPOSE 4001
CMD ["node", "--conditions", "production", "dist/src/index.js"]

# --- 3. Notification Service ---
FROM base AS notification-service-builder
WORKDIR /app
COPY tsconfig.base.json ./
WORKDIR /app/smr-backend/notification-service
COPY ./smr-backend/notification-service/package.json ./smr-backend/notification-service/tsconfig.json ./
RUN --mount=type=cache,target=/root/.npm npm install
RUN --mount=type=cache,target=/root/.npm npm install --save-dev typescript @types/node @types/express @types/cors @types/jsonwebtoken @types/morgan @types/amqplib
COPY ./smr-backend/notification-service/src ./src
RUN npm run build -- --noEmit false

FROM base AS notification-service-prod
USER node
WORKDIR /app
ENV NODE_ENV=production
COPY --chown=node:node ./smr-backend/notification-service/package.json ./package.json
RUN --mount=type=cache,target=/home/node/.npm,uid=1000,gid=1000 npm install --omit=dev
COPY --chown=node:node --from=notification-service-builder /app/smr-backend/notification-service/dist/ ./dist
EXPOSE 4002
CMD ["node", "--conditions", "production", "dist/src/index.js"]

# --- 4. Trip Service ---
FROM base AS trip-service-builder
WORKDIR /app
COPY tsconfig.base.json ./
WORKDIR /app/smr-backend/trip-service
COPY ./smr-backend/trip-service/package.json ./smr-backend/trip-service/tsconfig.json ./smr-backend/trip-service/prisma.config.ts ./
RUN --mount=type=cache,target=/root/.npm npm install
RUN --mount=type=cache,target=/root/.npm npm install --save-dev prisma typescript @types/node @types/express @types/cors @types/jsonwebtoken @types/morgan @types/amqplib
COPY ./smr-backend/trip-service/src ./src
RUN npm run prisma:generate
RUN npm run build -- --noEmit false
RUN mkdir -p ./dist/src/infrastructure/database/generated && cp -r ./src/infrastructure/database/generated/* ./dist/src/infrastructure/database/generated/

FROM base AS trip-service-prod
USER node
WORKDIR /app
ENV NODE_ENV=production
COPY --chown=node:node ./smr-backend/trip-service/package.json ./package.json
RUN --mount=type=cache,target=/home/node/.npm,uid=1000,gid=1000 npm install --omit=dev
COPY --chown=node:node --from=trip-service-builder /app/smr-backend/trip-service/dist/ ./dist
EXPOSE 4003
CMD ["node", "--conditions", "production", "dist/src/index.js"]

# --- 5. Payment Service ---
FROM base AS payment-service-builder
WORKDIR /app
COPY tsconfig.base.json ./
WORKDIR /app/smr-backend/payment-service
COPY ./smr-backend/payment-service/package.json ./smr-backend/payment-service/tsconfig.json ./
RUN --mount=type=cache,target=/root/.npm npm install
RUN --mount=type=cache,target=/root/.npm npm install --save-dev typescript @types/node @types/express @types/cors @types/jsonwebtoken @types/morgan @types/amqplib
COPY ./smr-backend/payment-service/src ./src
RUN npm run build -- --noEmit false

FROM base AS payment-service-prod
USER node
WORKDIR /app
ENV NODE_ENV=production
COPY --chown=node:node ./smr-backend/payment-service/package.json ./package.json
RUN --mount=type=cache,target=/home/node/.npm,uid=1000,gid=1000 npm install --omit=dev
COPY --chown=node:node --from=payment-service-builder /app/smr-backend/payment-service/dist/ ./dist
EXPOSE 4004
CMD ["node", "--conditions", "production", "dist/src/index.js"]
