services:
  shared-builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: shared-backend-build
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/smr-shared/node_modules
    command: pnpm --filter @sharemyride/shared run dev
    develop:
      watch:
        - action: sync
          path: ./smr-shared/src
          target: /app/smr-shared/src

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: user-service-dev
    tty: true
    ports:
      - "4001:4001"
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - ./smr-backend/user-service/.env
    environment:
      - NODE_ENV=development
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/smr-backend/user-service/node_modules
      - /app/smr-shared/node_modules
    develop:
      watch:
        - action: sync
          path: ./smr-backend/user-service/src
          target: /app/smr-backend/user-service/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./smr-backend/user-service/package.json
        - action: sync
          path: ./smr-shared/dist
          target: /app/smr-shared/dist

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: api-gateway-dev
    tty: true
    ports:
      - "4000:4000"
    env_file:
      - ./smr-backend/api-gateway/.env
    environment:
      - NODE_ENV=development
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/smr-backend/api-gateway/node_modules
      - /app/smr-shared/node_modules
    develop:
      watch:
        - action: sync
          path: ./smr-backend/api-gateway/src
          target: /app/smr-backend/api-gateway/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./smr-backend/api-gateway/package.json
        - action: sync
          path: ./smr-shared/dist
          target: /app/smr-shared/dist

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: notification-service-dev
    tty: true
    ports:
      - "4002:4002"
    env_file:
      - ./smr-backend/notification-service/.env
    environment:
      - NODE_ENV=development
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/smr-backend/notification-service/node_modules
      - /app/smr-shared/node_modules
    develop:
      watch:
        - action: sync
          path: ./smr-backend/notification-service/src
          target: /app/smr-backend/notification-service/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./smr-backend/notification-service/package.json
        - action: sync
          path: ./smr-shared/dist
          target: /app/smr-shared/dist

  trip-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: trip-service-dev
    tty: true
    ports:
      - "4003:4003"
      - "8080:8080"
    env_file:
      - ./smr-backend/trip-service/.env
    environment:
      - NODE_ENV=development
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/smr-backend/trip-service/node_modules
      - /app/smr-shared/node_modules
    develop:
      watch:
        - action: sync
          path: ./smr-backend/trip-service/src
          target: /app/smr-backend/trip-service/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./smr-backend/trip-service/package.json
        - action: sync
          path: ./smr-shared/dist
          target: /app/smr-shared/dist

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: payment-service-dev
    tty: true
    ports:
      - "4004:4004"
      - "8081:8080"
    env_file:
      - ./smr-backend/payment-service/.env
    environment:
      - NODE_ENV=development
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/smr-backend/payment-service/node_modules
      - /app/smr-shared/node_modules
    develop:
      watch:
        - action: sync
          path: ./smr-backend/payment-service/src
          target: /app/smr-backend/payment-service/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./smr-backend/payment-service/package.json
        - action: sync
          path: ./smr-shared/dist
          target: /app/smr-shared/dist

  communication-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: communication-service-dev
    tty: true
    ports:
      - "4005:4005"
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - ./smr-backend/communication-service/.env
    environment:
      - NODE_ENV=development
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/smr-backend/communication-service/node_modules
      - /app/smr-shared/node_modules
    develop:
      watch:
        - action: sync
          path: ./smr-backend/communication-service/src
          target: /app/smr-backend/communication-service/src
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./smr-backend/communication-service/package.json
        - action: sync
          path: ./smr-shared/dist
          target: /app/smr-shared/dist

  # --- Infrastructure Services ---

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./smr-infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./smr-infra/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./smr-infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./smr-infra/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./smr-infra/promtail/promtail-config.yaml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./smr-infra/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_LOG_LEVEL=warn
