services:
  # --- Backend Services ---
  api-gateway:
    build:
      context: .
      dockerfile: smr-backend/api-gateway/Dockerfile.prod
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production

  user-service:
    build:
      context: .
      dockerfile: smr-backend/user-service/Dockerfile.prod
    restart: always
    ports:
      - "4001:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production

  notification-service:
    build:
      context: .
      dockerfile: smr-backend/notification-service/Dockerfile.prod
    restart: always
    ports:
      - "4002:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production

  trip-service:
    build:
      context: .
      dockerfile: smr-backend/trip-service/Dockerfile.prod
    restart: always
    ports:
      - "4003:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production

  payment-service:
    build:
      context: .
      dockerfile: smr-backend/payment-service/Dockerfile.prod
    restart: always
    ports:
      - "4004:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production

  # --- Frontend Service ---
  frontend:
    build:
      context: .
      dockerfile: smr-frontend/Dockerfile.prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - api-gateway
