services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: user-service-prod
    restart: unless-stopped
    ports:
      - "4001:4001"
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - ./smr-backend/user-service/.env
    environment:
      - NODE_ENV=production

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: api-gateway-prod
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - ./smr-backend/api-gateway/.env
    environment:
      - NODE_ENV=production

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: notification-service-prod
    restart: unless-stopped
    ports:
      - "4002:4002"
    env_file:
      - ./smr-backend/notification-service/.env
    environment:
      - NODE_ENV=production

  trip-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: trip-service-prod
    restart: unless-stopped
    ports:
      - "4003:4003"
    env_file:
      - ./smr-backend/trip-service/.env
    environment:
      - NODE_ENV=production

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: payment-service-prod
    restart: unless-stopped
    ports:
      - "4004:4004"
    env_file:
      - ./smr-backend/payment-service/.env
    environment:
      - NODE_ENV=production

  communication-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: communication-service-prod
    restart: unless-stopped
    ports:
      - "4005:4005"
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - ./smr-backend/communication-service/.env
    environment:
      - NODE_ENV=production

  # --- Infrastructure Services ---

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./smr-infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./smr-infra/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./smr-infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
