packages:
  - smr-frontend
  - smr-backend/*
  - smr-shared
  - smr-ui
overrides:
  "@sharemyride/shared": "workspace:*"
  "@sharemyride/ui": "workspace:*"
onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
