packages:
  - smr-frontend
  - smr-backend/*
  - smr-shared
  - smr-ui
overrides:
  "@sharemyride/shared": "workspace:*"
  "@sharemyride/ui": "workspace:*"
allowBuilds:
  '@prisma/engines': true
  cpu-features: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
